const test=require('node:test'),assert=require('node:assert/strict'),W=require('../widget/workflow-core.js');
test('normalise email ProConnect',()=>assert.equal(W.email(' Alice@EXEMPLE.FR '),'alice@exemple.fr'));
test('retour motivé obligatoire',()=>assert.throws(()=>W.verifieDecision('A_CONTROLER','CONTROLE_CONFORMITE','RETOURNER','')));
test('retour et resoumission versionnés',()=>{let d=W.applique({Statut:'A_CONTROLER',Version:1},'RETOURNER','incomplet','CONTROLE_CONFORMITE');assert.equal(d.Statut,'A_CORRIGER');d=W.applique(d,'RESOUMETTRE','',d.EtapeActuelle);assert.equal(d.Version,2);assert.equal(d.Statut,'A_CONTROLER')});
test('verrouille après soumission',()=>assert.equal(W.peutModifier({Statut:'A_CONTROLER'}),false));
test('validation urgence et dates',()=>assert.equal(W.valide({Urgente:true,PersonnelConcerne:1,PaysDestination:1,DateDebutSejour:'2026-08-10',DateFinSejour:'2026-08-09',MotifDeplacement:'x'}).length,2));
test('calcul jours calendaires',()=>assert.equal(W.dateLimite('2026-08-10',3,'CALENDAIRES').toISOString().slice(0,10),'2026-08-07'));
test('calcul jours ouvrés',()=>assert.equal(W.dateLimite('2026-08-10',1,'OUVRES').toISOString().slice(0,10),'2026-08-07'));
test('transition BSPS terminale',()=>assert.equal(W.applique({Statut:'A_TRANSMETTRE_BSPS'},'TRANSMETTRE','', 'TRANSMISSION_BSPS').Statut,'TRANSMISE_BSPS'));
test('validation conformité crée étape chef de corps',()=>assert.deepEqual(W.transition('A_CONTROLER','VALIDER'),{statut:'A_VALIDER_CHEF_CORPS',etape:'VALIDATION_CHEF_CORPS',event:'VALIDATION'}));
test('décisions limitées par étape',()=>assert.deepEqual(W.decisionsPour('TRANSMISSION_BSPS'),['TRANSMETTRE']));
test('refuse une décision hors étape',()=>assert.throws(()=>W.verifieDecision('A_CONTROLER','CONTROLE_CONFORMITE','TRANSMETTRE','')));
test('resoumet vers le chef après retour du chef',()=>assert.deepEqual(W.cibleSoumission('A_CORRIGER','VALIDATION_CHEF_CORPS'),{statut:'A_VALIDER_CHEF_CORPS',etape:'VALIDATION_CHEF_CORPS',event:'RESOUMISSION',incrementVersion:true}));
test('premiere soumission cree une validation gestionnaire',()=>assert.deepEqual(W.cibleSoumission('BROUILLON','DEMANDE_INITIALE'),{statut:'SOUMISE',etape:'VALIDATION_GESTIONNAIRE',event:'SOUMISSION',incrementVersion:false}));
test('validation gestionnaire transmet a la conformite',()=>assert.deepEqual(W.transition('SOUMISE','VALIDER'),{statut:'A_CONTROLER',etape:'CONTROLE_CONFORMITE',event:'VALIDATION_GESTIONNAIRE'}));
test('retour gestionnaire resoumet au gestionnaire',()=>assert.deepEqual(W.cibleSoumission('A_CORRIGER','VALIDATION_GESTIONNAIRE'),{statut:'SOUMISE',etape:'VALIDATION_GESTIONNAIRE',event:'RESOUMISSION',incrementVersion:true}));
test('retour gestionnaire exige un motif',()=>assert.throws(()=>W.verifieDecision('SOUMISE','VALIDATION_GESTIONNAIRE','RETOURNER','')));
test('annulation est un statut terminal',()=>{
  assert.equal(W.TERMINAUX.has('ANNULEE'),true);
  assert.throws(()=>W.applique({Statut:'ANNULEE',Version:1},'VALIDER','','VALIDATION_GESTIONNAIRE'));
});
