(()=>{'use strict';const W=window.WorkflowCore;const state={demandes:[],pays:[],busy:false,grist:false};const $=s=>document.querySelector(s);
function notice(s){$('#alert').textContent=s||''}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function demo(){state.demandes=[{id:1,Reference:'DPE-2026-0001',PersonnelConcerne:'Camille Martin',PaysDestination:'Albanie',Statut:'A_CONTROLER',DateLimiteTraitement:'2026-07-18',Urgente:true},{id:2,Reference:'DPE-2026-0002',PersonnelConcerne:'Alex Bernard',PaysDestination:'Maroc',Statut:'A_CORRIGER',DateLimiteTraitement:'2026-08-01'}];state.pays=[{id:1,NomPays:'Albanie'},{id:2,NomPays:'Maroc'}];$('#mode').textContent='Mode démonstration — aucune donnée réelle';render()}
function render(){const now=new Date().toISOString().slice(0,10),late=state.demandes.filter(d=>d.DateLimiteTraitement&&d.DateLimiteTraitement<now&&!['TRANSMISE_BSPS','CLOTUREE'].includes(d.Statut)).length;$('#cards').innerHTML=[['Actions',state.demandes.length],['Urgentes',state.demandes.filter(d=>d.Urgente).length],['⚠ Hors délai',late],['À corriger',state.demandes.filter(d=>d.Statut==='A_CORRIGER').length]].map(x=>`<button class="card"><strong>${x[1]}</strong>${x[0]}</button>`).join('');const statuses=[...new Set(state.demandes.map(d=>d.Statut))];$('#filter').innerHTML='<option value="">Tous</option>'+statuses.map(s=>`<option>${esc(s)}</option>`).join('');filter();document.querySelector('[name=PaysDestination]').innerHTML='<option value="">Choisir</option>'+state.pays.map(p=>`<option value="${p.id}">${esc(p.NomPays)}</option>`).join('')}
function filter(){const q=$('#search').value.toLowerCase(),f=$('#filter').value,now=new Date().toISOString().slice(0,10);$('#rows').innerHTML=state.demandes.filter(d=>(!f||d.Statut===f)&&JSON.stringify(d).toLowerCase().includes(q)).map(d=>`<tr><td>${esc(d.Reference)}</td><td>${esc(d.PersonnelConcerne)}</td><td>${esc(d.PaysDestination)}</td><td>${esc(d.Statut)}</td><td class="${d.DateLimiteTraitement<now?'late':''}">${d.DateLimiteTraitement<now?'⚠ Hors délai — ':''}${esc(d.DateLimiteTraitement)}</td></tr>`).join('')||'<tr><td colspan="5">Aucun dossier correspondant.</td></tr>'}
async function init(){if(!window.grist){demo();return}state.grist=true;grist.ready({requiredAccess:'full'});try{const [d,p]=await Promise.all([grist.docApi.fetchTable('Demandes'),grist.docApi.fetchTable('Pays')]);state.demandes=rows(d);state.pays=rows(p).filter(x=>x.Actif!==false);$('#mode').textContent='Connecté à Grist';render()}catch(e){notice('Impossible de charger les données autorisées. Vérifiez les tables et les règles d’accès.')}}
function rows(t){return (t.id||[]).map((id,i)=>Object.fromEntries(Object.keys(t).map(k=>[k,t[k][i]])))}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{$('section:not([hidden])').hidden=true;$('#'+b.dataset.view).hidden=false});$('#cancel').onclick=()=>{$('#form').hidden=true;$('#dashboard').hidden=false};$('#search').oninput=filter;$('#filter').onchange=filter;
$('#request').onsubmit=async e=>{e.preventDefault();if(state.busy)return;const fd=new FormData(e.target),d=Object.fromEntries(fd);d.Urgente=fd.has('Urgente');const errors=W.valide(d);const file=fd.get('Pdf');if(file&&file.size&&(!file.name.toLowerCase().endsWith('.pdf')||file.type&&file.type!=='application/pdf'))errors.push('Seuls les fichiers PDF sont autorisés.');if(errors.length){notice(errors.join(' '));return}if(!confirm('Enregistrer ce brouillon ?'))return;state.busy=true;e.submitter.disabled=true;try{if(!state.grist){notice('Brouillon simulé : aucune écriture effectuée.');return}await grist.docApi.applyUserActions([['AddRecord','Demandes',null,{Statut:'BROUILLON',Version:1,DateDemande:Date.now()/1000,PersonnelConcerne:Number(d.PersonnelConcerne)||d.PersonnelConcerne,PaysDestination:Number(d.PaysDestination),DateDebutSejour:new Date(d.DateDebutSejour+'T12:00:00').getTime()/1000,DateFinSejour:new Date(d.DateFinSejour+'T12:00:00').getTime()/1000,MotifDeplacement:d.MotifDeplacement,Urgente:d.Urgente,JustificationUrgence:d.JustificationUrgence||''}]]);notice('Brouillon créé. Ajoutez le PDF dans la colonne Pièces jointes native Grist.')}catch(x){notice('Écriture refusée par Grist : '+x.message)}finally{state.busy=false;e.submitter.disabled=false}}
init()})();
